### ISSUE TITLE
Determine workflow for click-on-map lightbox.

### ISSUE THREAD

**Issue by nambuben** [UWAA/uwaa-2014#4]

**Comment by tifsev** [comment]
Workflow:

In MetaBoxes.php:
- add new array --
 array(
                        'name' => 'Tour Map Big Image',
                        'id'=> 'operator_big_map',
                        'type'=> 'text',
                        'desc'=> "Provide the URL for the Big Tour Map you have uploaded to WordPress (via the Media Gallery or this page). This is the image that will show in the lightbox on click."
                        )

In single-tours.php:
- add var on line 54 --  $bigMapURL = get_post_meta(get_the_id(), 'mb_operator_big_map', true);  
- add <a> tag to <img> on line 57. Use '<a href=" ' . esc_attr($bigMapURL) . '  ">

In WordPress dashboard: 
- add image of the large map (780 x 515) to media library. Then use the image's URL to add to metabox called Tour Map Big Image

**Comment by nambuben** [comment]
Looks good.  Implementing and will push up changes to master.  We have no pressing changes so I'm comfortable working on the main branch.
